blueprint:
  name: Shelly Detached Switch Fall Back - Single Button v1.0
  domain: automation
  description:
    "# Shelly Detached Switch Fall Back - Single Button v1.0**\n\n\
    Use a physical wall switch to control smart lights **without cutting power**.\n\
    Designed for Shelly Gen3/Gen4 devices in **detached mode**.\n\n\
    Thanks to the optional local Shelly fallback, basic interaction remains functional\n\
    even when Home Assistant is temporarily unavailable increasing the WAF factor.\n\n\
    ---\n\
    ## Supported Modes\n\n\
    Switch mode binary_sensor based wall switch\n\
    Lamp mode control a light directly\n\
    Fields marked with * are required by Home Assistant,\n\
    but may be ignored depending on your selected mode.\n"
  input:
    primary_input:
      name: "[Switch]* Binary sensor input"
      description: >
        REQUIRED by Home Assistant.
      selector:
        entity:
          domain: binary_sensor
    lamp_entity:
      name: "[Lamp]* Lamp entity"
      description: >
        REQUIRED when Action mode is 'lamp'.
        Ignored when Action mode is 'custom'.
      selector:
        entity:
          domain: light
    confirm_switch:
      name: "[Confirm]* switch" 
      description: >
        REQUIRED Shelly feedback output.
        Will be turned ON after each action to provide local confirmation.
      selector:
        entity:
          domain: switch

triggers:
  - trigger: state
    entity_id: !input primary_input
    from: "off"
    to: "on"
    id: Switch_on
  - trigger: state
    entity_id: !input primary_input
    from: "on"
    to: "off"
    id: Switch_off
conditions: []
actions:
  - alias: Check if Already in Correct State
    choose:
      - conditions:
          - condition: trigger
            id: Switch_on
          - condition: state
            entity_id: !input lamp_entity
            state: "on"
        sequence:
          - action: switch.turn_on
            metadata: {}
            target:
              entity_id: !input confirm_switch
            data: {}
      - conditions:
          - condition: trigger
            id: Switch_off
          - condition: state
            entity_id: !input lamp_entity
            state: "off"
        sequence:
          - action: switch.turn_on
            metadata: {}
            target:
              entity_id: !input confirm_switch
            data: {}
    default:
      - alias: Toggle On or Off
        choose:
          - conditions:
              - condition: trigger
                id: Switch_on
            sequence:
              - action: light.turn_on
                metadata: {}
                target:
                  entity_id: !input lamp_entity
                data: {}
              - wait_for_trigger:
                  - entity_id: !input lamp_entity
                    to: "on"
                    trigger: state
              - action: switch.turn_on
                metadata: {}
                target:
                  entity_id: !input confirm_switch
                data: {}
          - conditions:
              - condition: trigger
                id: Switch_off
            sequence:
              - action: light.turn_off
                metadata: {}
                target:
                  entity_id: !input lamp_entity
                data: {}
              - wait_for_trigger:
                  - entity_id: !input lamp_entity
                    to: "off"
                    trigger: state
              - action: switch.turn_on
                metadata: {}
                target:
                  entity_id: !input confirm_switch
                data: {}
mode: single
